// Generated For PUBGM NOTE : OUR OLD CHANNEL HAS BEEN BANNED PLEASE JOIN THE NEW ONE !! T.ME/ONLYY_DEVS (3.8.0) 
//SDK GENERATED BY @D_V_4

#include "../SDK.hpp"

namespace SDK
{
TNameEntryArray* FName::GNames = nullptr;
FUObjectArray* UObject::GUObjectArray = nullptr;
//---------------------By ARMP---------------------------
bool FWeakObjectPtr::IsValid() const {
if (ObjectSerialNumber == 0) {
return false;
}
if (ObjectIndex < 0) {
return false;
}
auto ObjectItem = UObject::GetGlobalObjects().GetItemByIndex(ObjectIndex);
if (!ObjectItem) {
return false;
}
if (!SerialNumbersMatch(ObjectItem)) {
return false;
}
return !(ObjectItem->IsUnreachable() || ObjectItem->IsPendingKill());
}
//---------------------By ARMP---------------------------
UObject* FWeakObjectPtr::Get() const {
if (IsValid()) {
auto ObjectItem = UObject::GetGlobalObjects().GetItemByIndex(ObjectIndex);
if (ObjectItem) {
return ObjectItem->Object;
}
}
return nullptr;
}
//---------------------By ARMP---------------------------
}

