#pragma once

// Generated For PUBGM NOTE : OUR OLD CHANNEL HAS BEEN BANNED PLEASE JOIN THE NEW ONE !! T.ME/ONLYY_DEVS (3.8.0) 
//SDK GENERATED BY @D_V_4

namespace SDK
{
//---------------------By ARMP---------------------------
//Script Structs
//---------------------By ARMP---------------------------

// UserDefinedStruct BP_STRUCT_VehiclePlaneSkinMapping_type.BP_STRUCT_VehiclePlaneSkinMapping_type
// 0x0018
struct FBP_STRUCT_VehiclePlaneSkinMapping_type
{
	int                                                OrginalID_0_035F8000705EAFE8164A73BF05CF7C94;             // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	int                                                SkinID_1_2D869240386FF4E567A70940014D8664;                // 0x0004(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	struct FString                                     iconURL_2_025050C0368B0D852A82EE78056E714C;               // 0x0008(0x0010) (Edit, BlueprintVisible, ZeroConstructor)
};

}

