#pragma once

// Generated For PUBGM NOTE : OUR OLD CHANNEL HAS BEEN BANNED PLEASE JOIN THE NEW ONE !! T.ME/ONLYY_DEVS (3.8.0) 
//SDK GENERATED BY @D_V_4

namespace SDK
{
//---------------------By ARMP---------------------------
//Classes
//---------------------By ARMP---------------------------

// BlueprintGeneratedClass FFLayoutTools.FFLayoutTools_C
// 0x0000 (0x0028 - 0x0028)
class UFFLayoutTools_C : public UBlueprintFunctionLibrary
{
public:

	static UClass* StaticClass()
	{
        static UClass *pStaticClass = 0;
        if (!pStaticClass)
            pStaticClass = UObject::FindClass("BlueprintGeneratedClass FFLayoutTools.FFLayoutTools_C");
		return pStaticClass;
	}


	static TMap<int, struct FBP_STRUCT_UIElemLayoutDetail> GetDefaultFFLayout(class UObject* __WorldContext);
};


}

