#pragma once

// Generated For PUBGM NOTE : OUR OLD CHANNEL HAS BEEN BANNED PLEASE JOIN THE NEW ONE !! T.ME/ONLYY_DEVS (3.8.0) 
//SDK GENERATED BY @D_V_4

namespace SDK
{
//---------------------By ARMP---------------------------
//Script Structs
//---------------------By ARMP---------------------------

// ScriptStruct NiagaraCore.NiagaraCompileHash
// 0x0010
struct FNiagaraCompileHash
{
	TArray<unsigned char>                              DataHash;                                                 // 0x0000(0x0010) (ZeroConstructor)
};

}

