#pragma once

// Generated For PUBGM NOTE : OUR OLD CHANNEL HAS BEEN BANNED PLEASE JOIN THE NEW ONE !! T.ME/ONLYY_DEVS (3.8.0) 
//SDK GENERATED BY @D_V_4

namespace SDK
{
//---------------------By ARMP---------------------------
//Script Structs
//---------------------By ARMP---------------------------

// UserDefinedStruct BP_STRUCT_GiftBPTable_type.BP_STRUCT_GiftBPTable_type
// 0x0014
struct FBP_STRUCT_GiftBPTable_type
{
	struct FString                                     GiftAniPath_0_116612401D7ECFD72A9F4BCF0B4BFE88;           // 0x0000(0x0010) (Edit, BlueprintVisible, ZeroConstructor)
	int                                                ID_1_121869C02EC2913D7CAEEFD406BAD054;                    // 0x0010(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
};

}

