#pragma once

// Generated For PUBGM NOTE : OUR OLD CHANNEL HAS BEEN BANNED PLEASE JOIN THE NEW ONE !! T.ME/ONLYY_DEVS (3.8.0) 
//SDK GENERATED BY @D_V_4

#include "../SDK.hpp"

namespace SDK
{
//---------------------By ARMP---------------------------
//Parameters
//---------------------By ARMP---------------------------

// Function FFLayoutTools.FFLayoutTools_C.GetDefaultFFLayout
struct UFFLayoutTools_C_GetDefaultFFLayout_Params
{
	class UObject*                                     __WorldContext;                                           // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
	TMap<int, struct FBP_STRUCT_UIElemLayoutDetail>    ReturnValue;                                              // (Parm, OutParm, ZeroConstructor, ReturnParm)
};

}

