#pragma once

// Generated For PUBGM NOTE : OUR OLD CHANNEL HAS BEEN BANNED PLEASE JOIN THE NEW ONE !! T.ME/ONLYY_DEVS (3.8.0) 
//SDK GENERATED BY @D_V_4

namespace SDK
{
//---------------------By ARMP---------------------------
//Script Structs
//---------------------By ARMP---------------------------

// UserDefinedStruct BP_STRUCT_CollectSeasonCfg_type.BP_STRUCT_CollectSeasonCfg_type
// 0x0028
struct FBP_STRUCT_CollectSeasonCfg_type
{
	int                                                ID_0_3189588013BBA9300AAD28310FA13D64;                    // 0x0000(0x0004) (Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData)
	unsigned char                                      UnknownData00[0x4];                                       // 0x0004(0x0004) MISSED OFFSET
	struct FString                                     Season_2_29E70F803D4CF324685E9C580C24296E;                // 0x0008(0x0010) (Edit, BlueprintVisible, ZeroConstructor)
	struct FString                                     StartTime_4_4D22FC8043F69A9C2765B677028A6F65;             // 0x0018(0x0010) (Edit, BlueprintVisible, ZeroConstructor)
};

}

